{% set name = "qsum" %}
{% set version = "0.2.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/QCoding/{{ name }}/archive/{{ version }}.tar.gz
  sha256: '8e53c087558dac9491354efbeeaeb097cf191716815603671671e46f8cd39702'

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5

test:
  files:
    - pytest.ini
    - mypy.ini
    - .pylintrc
  requires:
    - pytest >=4.4.0
    - pytest-pylint
  imports:
    - qsum
    - qsum.core
    - qsum.core.logic
    - qsum.core.constants
    - qsum.data
    - qsum.types
    - qsum.util
  commands:
    - python -c "import qsum; qsum.test(use_default_args=False)"

about:
  home: https://github.com/QCoding/qsum
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Python Checksumming Library'
  description: 'Intuitive and extendable checksumming for python objects'
  dev_url: https://github.com/QCoding/qsum

extra:
  recipe-maintainers:
    - QCoding
